kind: IptablesDnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: dnat01
spec:
  natGwDp: bbgw01
  eip: eipd01
  externalPort: '8888'
  internalIp: 192.168.0.5
  internalPort: '80'
  protocol: tcp
