apiVersion: v1
kind: Pod
metadata:
  name: busybox-default-and-storage
  annotations:
    ovn.kubernetes.io/logical_switch: ovn-default
    ovn.kubernetes.io/logical_switch: vlan-storage
spec:
  nodeName: okd-w2
  containers:
    - image: registry.yealinkops.com/common/base:centos7.6
      command:
        - sleep
        - "86400"
      name: busybox
