apiVersion: v1
kind: Pod
metadata:
  name: busybox-ovn-default
spec:
  nodeName: okd-w1
  containers:
    - image: registry.yealinkops.com/common/base:centos7.6
      command:
        - sleep
        - "86400"
      name: busybox
