apiVersion: v1
kind: Pod
metadata:
  name: busybox-1-nic
spec:
  containers:
    - image: registry.yealinkops.com/common/base:centos7.6
      command:
        - sleep
        - "86400"
      name: busybox
