apiVersion: v1
kind: Pod
metadata:
  name: nic-2-spec-ipmac
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: storage
    ovn.kubernetes.io/ip_address: 10.120.14.231
    ovn.kubernetes.io/mac_address: 00:00:00:53:6B:B6
    storage.default.ovn.kubernetes.io/ip_address: 10.120.13.231
    storage.default.ovn.kubernetes.io/mac_address: 00:00:00:53:6B:BB

spec:
  nodeName: okd-w2
  containers:
    - image: registry.yealinkops.com/common/base:centos7.6
      command:
        - sleep
        - "86400"
      name: busybox
