apiVersion: v1
kind: Pod
metadata:
  name: nic-2-spec-eth1
  namespace: default
spec:
  nodeName: okd-w2
  containers:
    - image: registry.yealinkops.com/common/base:centos7.6
      command:
        - sleep
        - "86400"
      name: busybox
