apiVersion: v1
kind: Pod
metadata:
  name: nic-2
  annotations:
    k8s.v1.cni.cncf.io/networks: storage/storage
spec:
  nodeName: okd-w2
  containers:
    - image: registry.yealinkops.com/common/base:centos7.6
      command:
        - sleep
        - "86400"
      name: busybox
