apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-config
  namespace: kubevirt
data:
  default-network-interface: masquerade
  feature-gates: DataVolumes,SRIOV,LiveMigration,CPUManager,CPUNodeDiscovery,Sidecar,Snapshot,HotplugVolumes
  selinuxLauncherType: virt_launcher.process
  smbios: |-
    Family: KubeVirt
    Manufacturer: KubeVirt
    Product: None
