---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipvlan-cni
  namespace: kube-system
  labels:
    tier: node
    app: ipvlan-cni
spec:
  selector:
    matchLabels:
      name: ipvlan-cni
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: ipvlan-cni
        name: ipvlan-cni
    spec:
      hostNetwork: true      
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: ipvlan-cni
        image: yldev.yealink.top/iaas/ipvlan-cni:0.2.3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-cni-net-dir
          mountPath: /host/etc/cni/net.d/
        - name: ipvlan-cni-config
          mountPath: /etc/cni/net.d/
      volumes:
        - name: host-cni-net-dir
          hostPath:
            path: /etc/cni/net.d/
        - name: ipvlan-cni-config
          configMap:
            name: ipvlan-cni-config


