# example:
# 172.18.0.0/16 是k8s pod子网（ipvlan）
# 172.18.0.1    是k8s pod子网的网关
# 172.27.0.0/16 是k8s service子网\
# 169.254.20.10/32 是nodelocaldns的IP（如果有装的话）
apiVersion: v1

kind: ConfigMap
metadata:
  name: ipvlan-cni-config
  namespace: kube-system
data:
  10-ipvlan.conf: |
    {
      "cniVersion":"0.3.1",
      "name": "ipvlannet",
      "type": "ipvlan",
      "master": "eth1",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "172.18.0.0/16",
        "range_start": "172.18.64.0",
        "range_end": "172.18.127.255",
        "exclude": [ "172.18.64.12/32", "172.18.64.16/30" ],
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "172.18.0.1" },
          { "dst": "172.27.0.0/16" },
          { "dst": "169.254.20.10/32" }
        ]
      }
    }
---

