apiVersion: v1
kind: Pod
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: vpc1-subnet1
  namespace: vpc1
  name: vpc-1-busybox04
spec:
  containers:
    - name: busybox
      image: registry.yealinkops.com/common/base:centos7.6
      command:
        - sleep
        - "8640000"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
