apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  type: "distributed"                   # centralized or distributed, when centralized external-gw-nodes config below will take effect. When distributed, every node in cluster must have a same nic and eip function will perform in distributed way.
  external-gw-nic: "eth1"               # The nic that will be bridged into ovs and act as overlay to underlay gateway
  nic-ip: "10.120.31.254/21"            # The ip and mask of the underlay physical gateway
  nic-mac: "60:f1:8a:54:c0:92"          # The mac of the underlay physical gateway
