apiVersion: kubeovn.io/v1
kind: VirtualIP
metadata:
  name: static-eip01
  labels:
    ovn-default: ""
    ovn.kubernetes.io/subnet: ovn-vpc-external-network
spec:
  namespace: kube-system
  subnet: ovn-vpc-external-network
  v4IpAddress: "172.20.10.201"
