kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: gw1
spec:
  vpc: vpc1
  subnet: vpc1-subnet1
  lanIp: 192.168.0.10
  eips:
    - eipCIDR: 172.20.10.200/24
      gateway: 172.20.10.2
  snatRules:
    - eip: 172.20.10.200
      internalCIDR: 192.168.0.0/24
