apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: Dual
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 172.20.10.0/24,fd00:172:20:10:/120
  gateway: 172.20.10.2
  excludeIps:
  - 172.20.10.1..172.20.10.200
