# 双网卡
apiVersion: v1
kind: Pod
metadata:
  namespace: bbvpc01
  name: bb-2-nic
  annotations:
    ovn.kubernetes.io/logical_switch: bbvpc01-subnet1
    k8s.v1.cni.cncf.io/networks: bbvpc01/bbvpc-nad-eth1
    bbvpc-nad-eth1.bbvpc01.ovn.kubernetes.io/logical_switch: bbvpc01-subnet1
spec:
  containers:
  - name: centos-sshd
    image: yealink.top/system/centos-sshd:latest
