kind: Deployment
apiVersion: apps/v1
metadata:
  name: snmp-exporter
  namespace: kube-system
  annotations:
    kubernetes.io/description: "snmp exporter"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      nodeName: hci-ctrl-3
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      hostNetwork: true
      containers:
        - name: snmp-exporter
          image: "ricardbejarano/snmp_exporter:latest"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/snmp_exporter
          volumeMounts:
            - mountPath: /snmp.yml
              name: snmp-exporter-conf
            - mountPath: /etc/localtime
              name: localtime
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      nodeSelector:
        kubernetes.io/os: "linux"
      volumes:
        - name: snmp-exporter-conf
          hostPath:
            path: /etc/snmp-exporter/snmp.yml
        - name: localtime
          hostPath:
            path: /etc/localtime
