apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: IPv4
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 172.20.10.0/24
  gateway: 172.20.10.1
  excludeIps:
  - 172.20.10.1..172.20.10.100
