apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: IPv4
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 10.120.13.0/24
  gateway: 10.120.13.254
  excludeIps:
  - 10.120.13.1..10.120.13.220
