apiVersion: v1
kind: Pod
metadata:
  name: centos-sshd-1
  namespace: underlay
  labels:
    app: centos-sshd
spec:
  containers:
  - name: centos-sshd
    image: yealink.top/system/centos-sshd
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
    - 10.5.200.10
    - 10.100.1.10
    options:
    - name: ndots
      value: "2"


