apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: bb1-subnet1
spec:
  cidrBlock: fd00:192:168::/120
  default: false
  disableGatewayCheck: false
  disableInterConnection: true
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: false
  private: false
  protocol: IPv6
  provider: ovn
  vpc: bb1
  namespaces:
  - bb1
