apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: bb1-subnet2
spec:
  cidrBlock: 192.168.1.0/24
  default: false
  disableGatewayCheck: false
  disableInterConnection: true
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: ovn
  vpc: bb1
  namespaces:
  - bb1
