kind: Service
apiVersion: v1
metadata:
  name: kube-ovn-controller
  namespace: kube-system
  labels:
    app: kube-ovn-controller
spec:
  type: LoadBalancer
  selector:
    app: kube-ovn-controller
  ports:
    - port: 10660
      name: metrics
