apiVersion: v1
kind: Service
metadata:
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
  labels:
    app.kubernetes.io/component: kubevirt
    kubevirt.io: ""
    prometheus.kubevirt.io: "true"
  name: yealink-kubevirt-prometheus-metrics
  namespace: kubevirt
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 443
    protocol: TCP
    targetPort: metrics
  selector:
    prometheus.kubevirt.io: "true"
  sessionAffinity: None
  type: LoadBalancer
