apiVersion: v1
kind: Pod
metadata:
  name: macvlan-centos-sshd
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan
spec:
  containers:
  - name: centos-sshd
    image: yealink.top/system/centos-sshd
